### ISSUE TITLE
Error using --install-sdk on compiled binary

### ISSUE THREAD

**Issue by vrnmthr** [MarcoG3/WhatsDump#17]
When called with the --install-sdk flag, crashes with the following message:

```
[INFO] Downloading and installing Android SDK...
[INFO] Android SDK url found: https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip
[################################] 100608/100608 - 00:00:09
[INFO] Extracting...
[INFO] Android SDK successfully extracted in android-sdk/
[INFO] Updating SDK from manager...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
[ERROR] Could not update SDK Manager
[ERROR] Failed to install Android SDK```

**Comment by MarcoG3** [comment]
This is definitely due to Java version. Can you run the following command and paste output?

`java -version`

**Comment by Acimaz** [comment]
I have the same error and have the following version:

`java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode, sharing)
`

**Comment by lalten** [comment]
I had the same error. Installing newer java does not help, instead you need to point your JAVA_HOME env var to an older java:
```sh
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
```

**Comment by alimony** [comment]
I solved this on a Mac by installing an older version of the Java JDK (version 8) and then setting:
```bash
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home
```
as previously suggested.
