### ISSUE TITLE
Cannot install python requirements

### ISSUE THREAD

**Issue by Erik0067** [MarcoG3/WhatsDump#33]
Hi,

I'm trying to run the python implementation of whatsdump on my Windows 10 computer.
I learned I have to install python 2.7.x. After choosing and installing python 2.7.9, I got these errors 
C:\Users\Erik\Downloads\WhatsDump-master\WhatsDump-master>python -m pip install requirements.txt
Downloading/unpacking requirements.txt
  Could not find any downloads that satisfy the requirement requirements.txt
Cleaning up...
No distributions at all found for requirements.txt
Storing debug log for failure in C:\Users\Erik\pip\pip.log

after running the command "python -m pip install requirements.txt". 

The contents of pip.log is:

------------------------------------------------------------
C:\Python27\lib\site-packages\pip\__main__.py run on 09/13/19 22:48:12
Downloading/unpacking requirements.txt
  Getting page https://pypi.python.org/simple/requirements.txt/
  Could not fetch URL https://pypi.python.org/simple/requirements.txt/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/requirements.txt/ when looking for download links for requirements.txt
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for requirements.txt:
  * https://pypi.python.org/simple/requirements.txt/
  Getting page https://pypi.python.org/simple/requirements.txt/
  Could not fetch URL https://pypi.python.org/simple/requirements.txt/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/requirements.txt/ when looking for download links for requirements.txt
  Could not find any downloads that satisfy the requirement requirements.txt
Cleaning up...
  Removing temporary dir c:\users\erik\appdata\local\temp\pip_build_Erik...
No distributions at all found for requirements.txt
Exception information:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "C:\Python27\lib\site-packages\pip\index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for requirements.txt

Did I install the wrong version or isn't the command correct?

Any help is very much appreciated, thanks in advance!

**Comment by Erik0067** [comment]
I solved this issue myself. I had to install version 2.7,16 (64 bit) and I had to enter the command "python -m pip install -r requirements.txt" (so with the -r argument)
