### ISSUE TITLE
Exception: adb="adb" is not executable. 

### ISSUE THREAD

**Issue by ceinem** [MarcoG3/WhatsDump#34]
Hi 
I'm getting the following error message when executing whatsDump. 

> [INFO] Cleaning WhatsApp...
[INFO] Moving extracted database into emulator...
Traceback (most recent call last):
  File "whatsdump.py", line 244, in <module>
    main()
  File "whatsdump.py", line 227, in main
    wa_emu.register_phone(msgstore_path, phone.country_code, phone.national_number, args.wa_verify, wa_code_callback)
  File "src/whatsapp.py", line 76, in register_phone
  File "src/tools.py", line 18, in get_viewclient
  return ViewClient(device=vc_adb, serialno=self.adb_client.serial, useuiautomatorhelper=True)
  File "com/dtmilano/android/viewclient.py", line 2475, in __init__
  File "com/dtmilano/android/common.py", line 168, in obtainAdbPath
Exception: adb="adb" is not executable. 
These files we unsuccessfully checked to find a suitable 'adb' executable:
    /Users/USERNAME/Downloads/WhatsDump-master/android-sdk/platform-tools/platform-tools/adb
    /Users/USERNAME/android/platform-tools/adb
    /Users/USERNAME/android-sdk/platform-tools/adb
    adb
    /Users/USERNAME/.cargo/bin/adb
    /Library/Frameworks/Python.framework/Versions/3.6/bin/adb
    /Library/Frameworks/Python.framework/Versions/3.6/bin/adb
    /usr/local/bin/adb
    /usr/bin/adb
    /bin/adb
    /usr/sbin/adb
    /sbin/adb
    /Applications/VMware Fusion.app/Contents/Public/adb
    /Library/TeX/texbin/adb
    /opt/X11/bin/adb
    /Applications/Wireshark.app/Contents/MacOS/adb
    [21469] Failed to execute script whatsdump

I'm executing the binaries on macOS Catalina. I've successfully installed all the dependencies and the sdk. 
It seems like the emulator is starting, but then having some problems with not finding the adb.

I tried setting the ANDROID_HOME variable to the android-sdk directory, but that didn't help. 

Any ideas or advice on what I could try?

Thank you very much!

**Comment by ceinem** [comment]
Sorry, fixed it. My ANDROID_HOME variable wrong. 
I had it set to: /Users/USERNAME/Downloads/WhatsDump-master/android-sdk/platform-tools instead of /Users/USERNAME/Downloads/WhatsDump-master/android-sdk
