### ISSUE TITLE
Error downloading & installing Android SDK

### ISSUE THREAD

**Issue by ZapdoZ** [MarcoG3/WhatsDump#41]
Trying to install the SDK gives me the following:
[INFO] Downloading and installing Android SDK...
[ERROR] Failed regex matching to find latest Android SDK (platform Windows)
[ERROR] Failed to install Android SDK

Tried this with the .exe release and with python 2.7, and I'm always getting the same error
I'm using Windows 10 x64

**Comment by klvenkatesh1994** [comment]
Any progress?

**Comment by shadowwalkersteam** [comment]
No, i'm still struggling with it

**Comment by SarahhMortada** [comment]
i m also getting the same error :(

**Comment by Lazza** [comment]
As a very quick fix, see #42.

**Comment by Dummy60** [comment]
Hey! I am a complete dummy in using python and I have the same problem as mentioned above when executing the .exe release. If anyone could fix the bug would it be possible to provide a link for a download of an updated, functioning .exe-file. Thx very much

**Comment by InsalataCondita** [comment]
I'm having the same problem, is there any update?

**Comment by prateekamana** [comment]
@InsalataCondita @Dummy60 @SarahhMortada @shadowwalkersteam 
Go to src/android_sdk.py and change the line 180 from 

` r = requests.get('https://developer.android.com/studio/')`

to 

` r = requests.get('https://web.archive.org/web/20190403122148/https://developer.android.com/studio/')`

as Lazza explained in #42

**Comment by MarlonVCendron** [comment]
> ` r=requests.get('https://web.archive.org/web/20190403122148/https://developer.android.com/studio/')`

That did not work for me.

```
[INFO] Downloading and installing Android SDK...
[ERROR] Failed GET request to developer.android.com
[ERROR] Failed to install Android SDK
```

**Comment by bibildibabeldibub** [comment]
Hey, i updatet the depencies with @yuvrajraghuvanshis commit, but i stil got an error, while updating the sdk: 

`    
[INFO] SDK tools directory already exists, skipping download & extraction...
[INFO] Updating SDK from manager...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
[ERROR] Could not update SDK Manager
[ERROR] Failed to install Android SDK
`

Has solved this error already ?

**Comment by yuvrajraghuvanshis** [comment]
> 
> 
> Hey, i updatet the depencies with @yuvrajraghuvanshis commit, but i stil got an error, while updating the sdk:
> 
> ` [INFO] SDK tools directory already exists, skipping download & extraction... [INFO] Updating SDK from manager... Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 5 more [ERROR] Could not update SDK Manager [ERROR] Failed to install Android SDK`
> 
> Has solved this error already ?

It looks like the already downloaded SDK is causing trouble. It's skipping fresh download of SDK. Try deleting that folder and re run. However I'm not sure.

**Comment by yuvrajraghuvanshis** [comment]
> 
> 
> Hey, i updatet the depencies with @yuvrajraghuvanshis commit, but i stil got an error, while updating the sdk:
> 
> ` [INFO] SDK tools directory already exists, skipping download & extraction... [INFO] Updating SDK from manager... Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 5 more [ERROR] Could not update SDK Manager [ERROR] Failed to install Android SDK`
> 
> Has solved this error already ?

@bibildibabeldibub It looks like the already downloaded SDK is causing trouble. It's skipping fresh download of SDK. Try deleting that folder and re run. However I'm not sure.

**Comment by bibildibabeldibub** [comment]
I done this but still got the error

**Comment by bibildibabeldibub** [comment]
> > Hey, i updatet the depencies with @yuvrajraghuvanshis commit, but i stil got an error, while updating the sdk:
> > ` [INFO] SDK tools directory already exists, skipping download & extraction... [INFO] Updating SDK from manager... Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 5 more [ERROR] Could not update SDK Manager [ERROR] Failed to install Android SDK`
> > Has solved this error already ?
> 
> @bibildibabeldibub It looks like the already downloaded SDK is causing trouble. It's skipping fresh download of SDK. Try deleting that folder and re run. However I'm not sure.

Maybe it is the result of wrong jdk or jre ?

**Comment by yuvrajraghuvanshis** [comment]
@bibildibabeldibub I looked it up, [try this](https://stackoverflow.com/a/51644855)

**Comment by yuvrajraghuvanshis** [comment]
> 
> 
> > > Hey, i updatet the depencies with @yuvrajraghuvanshis commit, but i stil got an error, while updating the sdk:
> > > ` [INFO] SDK tools directory already exists, skipping download & extraction... [INFO] Updating SDK from manager... Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 5 more [ERROR] Could not update SDK Manager [ERROR] Failed to install Android SDK`
> > > Has solved this error already ?
> > 
> > 
> > @bibildibabeldibub It looks like the already downloaded SDK is causing trouble. It's skipping fresh download of SDK. Try deleting that folder and re run. However I'm not sure.
> 
> Maybe it is the result of wrong jdk or jre ?

@bibildibabeldibub I looked it up, [try this](https://stackoverflow.com/a/51644855)

**Comment by bibildibabeldibub** [comment]
> > > > Hey, i updatet the depencies with @yuvrajraghuvanshis commit, but i stil got an error, while updating the sdk:
> > > > ` [INFO] SDK tools directory already exists, skipping download & extraction... [INFO] Updating SDK from manager... Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 5 more [ERROR] Could not update SDK Manager [ERROR] Failed to install Android SDK`
> > > > Has solved this error already ?
> > > 
> > > 
> > > @bibildibabeldibub It looks like the already downloaded SDK is causing trouble. It's skipping fresh download of SDK. Try deleting that folder and re run. However I'm not sure.
> > 
> > 
> > Maybe it is the result of wrong jdk or jre ?
> 
> @bibildibabeldibub I looked it up, [try this](https://stackoverflow.com/a/51644855)

Ah yes i found it too, thx it started working.

**Comment by yuvrajraghuvanshis** [comment]
> > > > > Hey, i updatet the depencies with @yuvrajraghuvanshis commit, but i stil got an error, while updating the sdk:
> > > > > ` [INFO] SDK tools directory already exists, skipping download & extraction... [INFO] Updating SDK from manager... Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156) at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75) at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73) at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48) Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 5 more [ERROR] Could not update SDK Manager [ERROR] Failed to install Android SDK`
> > > > > Has solved this error already ?
> > > > 
> > > > 
> > > > @bibildibabeldibub It looks like the already downloaded SDK is causing trouble. It's skipping fresh download of SDK. Try deleting that folder and re run. However I'm not sure.
> > > 
> > > 
> > > Maybe it is the result of wrong jdk or jre ?
> > 
> > @bibildibabeldibub I looked it up, [try this](https://stackoverflow.com/a/51644855)
> 
> Ah yes i found it too, thx it started working. 
> 
> 

Glad to hear that.
