### ISSUE TITLE
Installation hangs out

### ISSUE THREAD

**Issue by diqipib** [MarcoG3/WhatsDump#43]
```
D:\WhatsDump-master>python whatsdump.py --install-sdk

 _    _ _           _      ______
| |  | | |         | |     |  _  \
| |  | | |__   __ _| |_ ___| | | |_   _ _ __ ___  _ __
| |/\| | '_ \ / _` | __/ __| | | | | | | '_ ` _ \| '_ \
\  /\  / | | | (_| | |_\__ \ |/ /| |_| | | | | | | |_) |
 \/  \/|_| |_|\__,_|\__|___/___/  \__,_|_| |_| |_| .__/
                                                 | |
                                                 |_|
                        v0.2 beta

[INFO] SDK tools directory already exists, skipping download & extraction...
[INFO] Updating SDK from manager...
[=======================================] 100% Computing updates...
[INFO] Accepting SDK licenses..
All SDK package licenses accepted.======] 100% Computing updates...
```
I wait 10-15 minutes and then stopped it with CTRL+C.
That's what I see in output:

```Traceback (most recent call last):
  File "whatsdump.py", line 244, in <module>
    main()
  File "whatsdump.py", line 78, in main
    if not sdk.install():
  File "D:\WhatsDump-master\src\android_sdk.py", line 59, in install
    s2 = self._run_cmd_sdkmanager("--list")
  File "D:\WhatsDump-master\src\android_sdk.py", line 218, in _run_cmd_sdkmanager
    return self._run_cmd(CommandType.TOOLS_BIN, 'sdkmanager', args, wait, input, show)
  File "D:\WhatsDump-master\src\android_sdk.py", line 247, in _run_cmd
    wait, input, show)
  File "D:\WhatsDump-master\src\android_sdk.py", line 269, in _run_raw_cmd
    proc.wait()
  File "C:\Python27\lib\subprocess.py", line 693, in wait
    _subprocess.INFINITE)
KeyboardInterrupt```

**Comment by diragb** [comment]
same here, any update?

**Comment by gdinit** [comment]
This fixed it for me: https://github.com/MarcoG3/WhatsDump/issues/18#issuecomment-510388180
