### ISSUE TITLE
Error on ADB version

### ISSUE THREAD

**Issue by p5panam** [MarcoG3/WhatsDump#7]
I have this error... any ideas to fix it?

[INFO] Starting emulator...
emulator: WARNING: Crash service did not start

HAX is working and emulator runs in fast virt mode.
emulator: Cold boot: requested by the user
[INFO] Trying to register phone on emulator... (may take few minutes)
[INFO] Installing WhatsApp...
[INFO] Cleaning WhatsApp...
[INFO] Moving extracted database into emulator...
Traceback (most recent call last):
  File "whatsdump.py", line 244, in <module>
    main()
  File "whatsdump.py", line 227, in main
    wa_emu.register_phone(msgstore_path, phone.country_code, phone.national_number, args.wa_verify, wa_code_callback)
  File "C:\Python27\src\whatsapp.py", line 76, in register_phone
    vc = tools.get_viewclient()
  File "C:\Python27\src\tools.py", line 13, in get_viewclient
    vc_adb = VcAdbClient(self.adb_client.serial)
  File "C:\Python27\lib\site-packages\com\dtmilano\android\adb\adbclient.py", line 187, in __init__
    self.checkVersion(ignoreversioncheck)
  File "C:\Python27\lib\site-packages\com\dtmilano\android\adb\adbclient.py", line 384, in checkVersion
    "ERROR: Incorrect ADB server version %s (expecting one of %s)" % (version, VALID_ADB_VERSIONS))
RuntimeError: ERROR: Incorrect ADB server version 00040029 (expecting one of ['00040028', '00040027', '00040024', '00040023', '00040020', '0004001f'])

**Comment by MarcoG3** [comment]
Looks like some ADB version check that 3rd party module is making. Should be fixed in 1e20fd1

**Comment by p5panam** [comment]
Seems another check is required on another file. "adbclient.py"

HAX is working and emulator runs in fast virt mode.
emulator: Cold boot: requested by the user
[INFO] Trying to register phone on emulator... (may take few minutes)
[INFO] Installing WhatsApp...
[INFO] Cleaning WhatsApp...
[INFO] Moving extracted database into emulator...
9999
Traceback (most recent call last):
  File "whatsdump.py", line 244, in <module>
    main()
  File "whatsdump.py", line 227, in main
    wa_emu.register_phone(msgstore_path, phone.country_code, phone.national_number, args.wa_verify, wa_code_callback)
  File "C:\Python27\src\whatsapp.py", line 76, in register_phone
    vc = tools.get_viewclient()
  File "C:\Python27\src\tools.py", line 18, in get_viewclient
    return ViewClient(device=vc_adb, serialno=self.adb_client.serial, useuiautomatorhelper=True)
  File "C:\Python27\lib\site-packages\com\dtmilano\android\viewclient.py", line 2577, in __init__
    self.uiAutomatorHelper = UiAutomatorHelper(device)
  File "C:\Python27\lib\site-packages\com\dtmilano\android\uiautomator\uiautomatorhelper.py", line 128, in __init__
    self.__runTests()
  File "C:\Python27\lib\site-packages\com\dtmilano\android\uiautomator\uiautomatorhelper.py", line 187, in __runTests
    newAdbClient = AdbClient(self.adbClient.serialno, self.adbClient.hostname, self.adbClient.port, timeout=None)
  File "C:\Python27\lib\site-packages\com\dtmilano\android\adb\adbclient.py", line 187, in __init__
    self.checkVersion(ignoreversioncheck)
  File "C:\Python27\lib\site-packages\com\dtmilano\android\adb\adbclient.py", line 384, in checkVersion
    "ERROR: Incorrect ADB server version %s (expecting one of %s)" % (version, VALID_ADB_VERSIONS))
RuntimeError: ERROR: Incorrect ADB server version 00040029 (expecting one of ['00040028', '00040027', '00040024', '00040023', '00040020', '0004001f'])

**Comment by MarcoG3** [comment]
Can you tell me the OS you're running WhatsDump in?
Also, please paste the content of the file in `WhatsApp-Dump/android-sdk/platform-tools/source.properties` so I can take a look at SDK version. Since the 3rd party module is not very flexible, I guess a downgrade to a supported SDK would be needed.

**Comment by p5panam** [comment]
i fixed adding on adbclient.py at line 380
Just add that version on the list.

VALID_ADB_VERSIONS = ["00040029", "00040028",

**Comment by MorphBZH** [comment]
I had the same error, add 40020029 too, to resolve it.

**Comment by MarcoG3** [comment]
This needs a more robust bugfix, I will commit a fix as soon as I have some free time.
