### ISSUE TITLE
Emulator Error

### ISSUE THREAD

**Issue by Unixcornio** [MarcoG3/WhatsDump#8]
I have this error:

[INFO] Starting emulator...
Windows Hypervisor Platform accelerator is operational
emulator: Cold boot: requested by the user
[INFO] Trying to register phone on emulator... (may take few minutes)
[INFO] Installing WhatsApp...
[INFO] Cleaning WhatsApp...
[INFO] Moving extracted database into emulator...
9999
Traceback (most recent call last):
  File "whatsdump.py", line 244, in <module>
    main()
  File "whatsdump.py", line 227, in main
    wa_emu.register_phone(msgstore_path, phone.country_code, phone.national_number, args.wa_verify, wa_code_callback)
  File "C:\WhatsDump-master\src\whatsapp.py", line 76, in register_phone
    vc = tools.get_viewclient()
  File "C:\WhatsDump-master\src\tools.py", line 18, in get_viewclient
    return ViewClient(device=vc_adb, serialno=self.adb_client.serial, useuiautomatorhelper=True)
  File "C:\Python2.7\lib\site-packages\com\dtmilano\android\viewclient.py", line 2577, in __init__
    self.uiAutomatorHelper = UiAutomatorHelper(device)
  File "C:\Python2.7\lib\site-packages\com\dtmilano\android\uiautomator\uiautomatorhelper.py", line 134, in __init__
    raise ex
RuntimeError: Cannot connect to http://localhost:9999

**Comment by MarcoG3** [comment]
This happens randomly, it is a bug of third party library I'm using so I need to take a closer look. Temporary solution would be to re-run the script.

**Comment by MarcoG3** [comment]
Can you specify which OS you're using?

**Comment by Unixcornio** [comment]
Im sorry. Effectively. When testing again it has worked. I have Windows 10 (1809).

**Comment by ceinem** [comment]
I'm sometimes getting this same error. Running Ubuntu 18
